version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: postgres-knack
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres_username
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin-knack
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres